'use client';

import Link from 'next/link';
import { AlertTriangle, ArrowLeft, Leaf, CloudSun, TrendingUp, ShieldAlert } from 'lucide-react';
import { useLanguage } from '@/lib/language';

export function DisclaimerClient() {
  const { t, lang } = useLanguage();

  return (
    <div className="max-w-4xl mx-auto py-8 px-2 md:px-6">
      
      {/* Back button */}
      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-foreground transition-colors group"
      >
        <ArrowLeft className="h-4 w-4 group-hover:-translate-x-1 transition-transform" />
        <span>{lang === "hi" ? "मुख्य पृष्ठ पर वापस जाएं" : lang === "kn" ? "ಹೋಮ್ ಪೇಜ್‌ಗೆ ಹಿಂತಿರುಗಿ" : "Back to home"}</span>
      </Link>

      {/* Header card */}
      <div className="rounded-2xl border border-border/40 bg-card/25 backdrop-blur-md p-6 md:p-8 mb-8 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 rounded-full bg-emerald-500/5 blur-2xl pointer-events-none" />
        <div className="flex items-center gap-3 mb-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-500 shadow shadow-emerald-500/10">
            <AlertTriangle className="h-5 w-5" />
          </div>
          <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-500 dark:text-emerald-400">
            {lang === "hi" ? "कानूनी अस्वीकरण" : lang === "kn" ? "ಕಾನೂನು ಹಕ್ಕುತ್ಯಾಗ" : "Legal Disclaimer"}
          </span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground font-display">
          {lang === "hi" ? "सलाहकार अस्वीकरण" : lang === "kn" ? "ಸಲಹಾ ಹಕ್ಕುತ್ಯಾಗ" : "Advisory Disclaimer"}
        </h1>
        <p className="text-xs text-muted-foreground mt-2">
          {lang === "hi" ? "अंतिम अद्यतन: 5 जून, 2026" : lang === "kn" ? "ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಿದ್ದು: ಜೂನ್ 5, 2026" : "Last Updated: June 5, 2026"}
        </p>
      </div>

      {/* Policy contents */}
      <div className="glass-panel rounded-2xl p-6 md:p-8 space-y-6 text-xs md:text-sm text-muted-foreground leading-relaxed">
        
        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <ShieldAlert className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            {lang === "hi" ? "1. सामान्य अस्वीकरण" : lang === "kn" ? "1. ಸಾಮಾನ್ಯ ಹಕ್ಕುತ್ಯಾಗ" : "1. General Disclaimer"}
          </h2>
          <p>
            {lang === "hi"
              ? "KrishiAI प्लेटफ़ॉर्म पर प्रदान की गई सभी जानकारी, जिसमें फसल भविष्यवाणियां, रोग निदान, मंडी कीमतें, सरकारी योजनाओं की पात्रता और मौसम सलाह शामिल हैं, केवल सूचनात्मक और शैक्षिक उद्देश्यों के लिए है।"
              : lang === "kn"
                ? "ಕೃಷಿAI ವೇದಿಕೆಯಲ್ಲಿ ಒದಗಿಸಲಾದ ಬೆಳೆ ಮುನ್ಸೂಚನೆಗಳು, ರೋಗ ಪತ್ತೆಹಚ್ಚುವಿಕೆ, ಮಂಡಿ ಬೆಲೆಗಳು ಮತ್ತು ಹವಾಮಾನ ವಿವರಗಳು ಕೇವಲ ಮಾಹಿತಿ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ."
                : "All information provided on the KrishiAI platform, including but not limited to crop predictions, disease diagnoses, mandi prices, government schemes eligibility, and weather advisories, is for informational and educational purposes only."}
          </p>
          <p>
            {lang === "hi"
              ? "सामग्री \"जैसी है\" और \"जैसी उपलब्ध है\" के आधार पर प्रदान की जाती है। हम सिस्टम द्वारा उत्पन्न एआई सुझावों की सटीकता, पूर्णता या विश्वसनीयता के बारे में किसी भी प्रकार की कोई वारंटी नहीं देते हैं।"
              : lang === "kn"
                ? "ಮಾಹಿತಿಯನ್ನು ಇದ್ದ ಹಾಗೆ ನೀಡಲಾಗುತ್ತದೆ. ಸಿಸ್ಟಮ್ ಒದಗಿಸುವ AI ಸಲಹೆಗಳ ನಿಖರತೆ ಅಥವಾ ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಬಗ್ಗೆ ನಾವು ಯಾವುದೇ ಗ್ಯಾರಂಟಿ ನೀಡುವುದಿಲ್ಲ."
                : "The content is provided on an \"as is\" and \"as available\" basis. We make no representations or warranties of any kind, express or implied, as to the accuracy, completeness, or reliability of the AI suggestions generated by the system."}
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <Leaf className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            {lang === "hi" ? "2. एआई संयंत्र रोग का पता लगाना और सिफारिशें" : lang === "kn" ? "2. AI ಸಸ್ಯ ರೋಗ ಪತ್ತೆ ಮತ್ತು ಶಿಫಾರಸುಗಳು" : "2. AI Plant Disease Detection & Recommendations"}
          </h2>
          <p>
            {lang === "hi"
              ? "हमारा फसल रोग एआई उपयोगकर्ता द्वारा सबमिट की गई तस्वीरों को संसाधित करके पत्ती की क्षति, कीड़ों के खाने या फंगस के पैटर्न को पहचानता है।"
              : lang === "kn"
                ? "ನಮ್ಮ ಬೆಳೆ ರೋಗ ಪತ್ತೆಹಚ್ಚುವಿಕೆ AI ಬಳಕೆದಾರರು ಸಲ್ಲಿಸುವ ಫೋಟೋಗಳ ಆಧಾರದ ಮೇಲೆ ರೋಗದ ಮಾದರಿಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ."
                : "Our Crop Disease AI processes user-submitted photos to recognize patterns representing leaf damage, insect feeding, or mold."}
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              {lang === "hi" ? "मशीन लर्निंग मॉडल कभी-कभी गलत परिणाम दे सकते हैं या दुर्लभ बीमारियों का पता लगाने में विफल हो सकते हैं।" : lang === "kn" ? "ಯಂತ್ರ ಕಲಿಕೆ ಮಾಡೆಲ್ ರೋಗ ಪತ್ತೆಯಲ್ಲಿ ಅಪರೂಪದ ತಪ್ಪುಗಳನ್ನು ಮಾಡಬಹುದು." : "Machine learning models can experience false positives or fail to detect rare disease variants."}
            </li>
            <li>
              {lang === "hi" ? "अनुशंसित कीटनाशक, कवकनाशी या जैविक उपचार केवल सुझाव हैं और रासायनिक लेबल के साथ सत्यापित किए जाने चाहिए।" : lang === "kn" ? "ಸೂಚಿಸಲಾದ ಕೀಟನಾಶಕಗಳು ಕೇವಲ ಸಲಹೆಗಳಾಗಿದ್ದು, ಅಧಿಕೃತ ರಾಸಾಯನಿಕ ಲೇಬಲ್ ವೀಕ್ಷಿಸಿ ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಬೇಕು." : "Recommended pesticides, insecticides, fungicides, or organic treatments represent suggestions and must be cross-verified with manufacturers' chemical labels."}
            </li>
            <li>
              {lang === "hi" ? "गलत रासायनिक उपयोग या मॉडल त्रुटि से होने वाले फसल नुकसान या वित्तीय नुकसान के लिए हम जिम्मेदार नहीं हैं।" : lang === "kn" ? "ತಪ್ಪು ರಾಸಾಯನಿಕ ಬಳಕೆ ಅಥವಾ ಮಾಡೆಲ್ ಲೋಪದಿಂದ ಉಂಟಾಗುವ ಯಾವುದೇ ಬೆಳೆ ಅಥವಾ ಆರ್ಥಿಕ ನಷ್ಟಕ್ಕೆ ನಾವು ಜವಾಬ್ದಾರರಲ್ಲ." : "We are not responsible for any crop failure, soil degradation, or physical/financial harm resulting from incorrect chemical application ratios or model error."}
            </li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <CloudSun className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            {lang === "hi" ? "3. मौसम पूर्वानुमान अलर्ट" : lang === "kn" ? "3. ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು" : "3. Weather Intelligence Alerts"}
          </h2>
          <p>
            {lang === "hi"
              ? "मौसम डेटा तीसरे पक्ष के मौसम सेवा प्रदाताओं से प्राप्त किया जाता है। मौसम का पूर्वानुमान स्वाभाविक रूप से अनिश्चित होता है। हम तापमान में अचानक बदलाव, बिन मौसम बारिश या ओलावृष्टि के लिए उत्तरदायी नहीं हैं।"
              : lang === "kn"
                ? "ಹವಾಮಾನ ಡೇಟಾವನ್ನು ಮೂರನೇ ವ್ಯಕ್ತಿಗಳಿಂದ ಪಡೆಯಲಾಗುತ್ತದೆ. ಹವಾಮಾನ ಮುನ್ಸೂಚನೆಯು ಅನಿಶ್ಚಿತತೆಯಿಂದ ಕೂಡಿದ್ದು, ತಾಪಮಾನದ ಹಠಾತ್ ಬದಲಾವಣೆಗಳು ಅಥವಾ ಅನಿರೀಕ್ಷಿತ ಮಳೆಗೆ ನಾವು ಜವಾಬ್ದಾರರಲ್ಲ."
                : "Weather data is compiled from third-party meteorological providers. While we utilize automatic failover mechanisms to provide the most recent information, weather forecasting is inherently probabilistic. We cannot be held liable for sudden shifts in temperature, unpredicted rainfall, or hail storms that affect your crops."}
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <TrendingUp className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            {lang === "hi" ? "4. लाइव मंडी भाव और बाजार अलर्ट" : lang === "kn" ? "4. ಲೈವ್ ಮಂಡಿ ಬೆಲೆಗಳು ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಎಚ್ಚರಿಕೆಗಳು" : "4. Live Mandi Prices & Market Alerts"}
          </h2>
          <p>
            {lang === "hi"
              ? "बाजार कीमतें एपीएमसी बाजार डैशबोर्ड के आधार पर गतिशील रूप से अपडेट की जाती हैं। नेटवर्क विलंबता और भौगोलिक अंतर के कारण:"
              : lang === "kn"
                ? "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳನ್ನು APMC ಯಿಂದ ನವೀಕರಿಸಲಾಗುತ್ತದೆ. ನೆಟ್‌ವರ್ಕ್ ಸಮಸ್ಯೆಗಳಿಂದಾಗಿ:"
                : "Market prices are updated dynamically based on APMC market dashboards. Due to network latency, geographical differences, and loading variables:"}
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>{lang === "hi" ? "प्रदर्शित कीमतें स्थानीय भौतिक मंडी दरों से पीछे रह सकती हैं।" : lang === "kn" ? "ತೋರಿಸುವ ಬೆಲೆಗಳು ಮಾರುಕಟ್ಟೆಯ ದರಕ್ಕಿಂತ ಸ್ವಲ್ಪ ತಡವಾಗಿರಬಹುದು." : "The prices displayed might lag behind local physical mandi rates."}</li>
            <li>{lang === "hi" ? "निर्धारित लक्ष्य सूचनाएं आपकी सहायता के लिए हैं और तुरंत सक्रिय होने की गारंटी नहीं हैं।" : lang === "kn" ? "ನಿಗದಿಪಡಿಸಿದ ಅಲರ್ಟ್‌ಗಳು ರೈತರ ಸಹಾಯಕ್ಕಾಗಿ ಮಾತ್ರವಾಗಿದ್ದು, ತಕ್ಷಣ ರನ್ ಆಗುವ ಭರವಸೆ ಇಲ್ಲ." : "Set target notifications are alerts to assist you and are not guaranteed to fire instantly."}</li>
            <li>{lang === "hi" ? "KrishiAI फसल व्यापार घाटे के लिए दायित्व स्वीकार नहीं करता है।" : lang === "kn" ? "ಕೃಷಿAI ಯಾವುದೇ ಕೃಷಿ ವ್ಯಾಪಾರ ನಷ್ಟಗಳಿಗೆ ಹೊಣೆಯಾಗುವುದಿಲ್ಲ." : "KrishiAI does not guarantee profit margins or bear liability for crop trading losses."}</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            🏛️ {lang === "hi" ? "5. सरकारी योजनाओं का प्रतिनिधित्व अस्वीकरण" : lang === "kn" ? "5. ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಪ್ರಾತಿನಿಧ್ಯ ಹಕ್ಕುತ್ಯಾಗ" : "5. Government Schemes Eligibility & Representation"}
          </h2>
          <p>
            {lang === "hi"
              ? "KrishiAI पीएम-किसान, पीएमएफबीवाई और केसीसी जैसी योजनाओं के लिए पात्रता जांच उपकरण प्रदान करता है।"
              : lang === "kn"
                ? "KrishiAI ಪಿಎಂ-ಕಿಸಾನ್, ಪಿಎಂಎಫ್‌ಬಿವೈ ಮುಂತಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಅರ್ಹತೆ ಪರಿಶೀಲನೆ ಸಾಧನವನ್ನು ನೀಡುತ್ತದೆ."
                : "KrishiAI offers an interactive eligibility tool for central schemes such as PM-Kisan, PMFBY, and KCC."}
          </p>
          <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
            <strong>{lang === "hi" ? "सरकारी प्रतिनिधित्व अस्वीकरण:" : lang === "kn" ? "ಸರ್ಕಾರಿ ಪ್ರಾತಿನಿಧ್ಯ ಹಕ್ಕುತ್ಯಾಗ:" : "GOVERNMENT REPRESENTATION DISCLAIMER:"}</strong>{' '}
            {lang === "hi"
              ? "KrishiAI एक निजी, स्वतंत्र और छात्रों द्वारा संचालित AI एप्लिकेशन है। हम कृषि मंत्रालय, भारत सरकार या किसी राज्य सरकार की एजेंसियों से संबद्ध नहीं हैं। सभी लिंक आधिकारिक सरकारी पोर्टलों की ओर ले जाते हैं।"
              : lang === "kn"
                ? "ಕೃಷಿAI ಖಾಸಗಿ, ಸ್ವತಂತ್ರ ಅಪ್ಲಿಕೇಶನ್ ಆಗಿದೆ. ನಾವು ಭಾರತ ಸರ್ಕಾರ ಅಥವಾ ಯಾವುದೇ ಕೃಷಿ ಇಲಾಖೆಯೊಂದಿಗೆ ಸಂಯೋಜನೆ ಹೊಂದಿಲ್ಲ. ಎಲ್ಲಾ ಲಿಂಕ್‌ಗಳು ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್‌ಗಳಿಗೆ ದಾರಿ ತೋರಿಸುತ್ತವೆ."
                : "KrishiAI is a private, independent student-led AI application. We are NOT associated, endorsed, or affiliated with the Ministry of Agriculture, the Indian Government, or any State Government agencies. All applications and registration links point to public, official government portals."}
          </div>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            📞 {lang === "hi" ? "6. सहायता प्रश्न" : lang === "kn" ? "6. ಸಹಾಯ ಪ್ರಶ್ನೆಗಳು" : "6. Support Questions"}
          </h2>
          <p>
            {lang === "hi"
              ? "यदि आपको पेशेवर कृषि सहायता की आवश्यकता है, तो हम प्रमाणित कृषि वैज्ञानिकों से परामर्श करने की सलाह देते हैं। प्रश्नों के लिए संपर्क करें: adityaoutlier5@gmail.com।"
              : lang === "kn"
                ? "ನಿಮಗೆ ವೃತ್ತಿಪರ ಕೃಷಿ ಸಹಾಯದ ಅಗತ್ಯವಿದ್ದರೆ ಕೃಷಿ ವಿಜ್ಞಾನಿಗಳ ಸಲಹೆ ಪಡೆಯಲು ಸೂಚಿಸುತ್ತೇವೆ. ಇಮೇಲ್: adityaoutlier5@gmail.com."
                : "If you require professional agricultural support, we advise consulting with certified botanists, regional APMC officials, or local government agriculture officers. Contact us at: adityaoutlier5@gmail.com."}
          </p>
        </section>

      </div>
    </div>
  );
}
