'use client';

import Link from 'next/link';
import { AlertTriangle, ArrowLeft, Leaf, CloudSun, TrendingUp, ShieldAlert } from 'lucide-react';
import { useLanguage } from '@/lib/language';

export function DisclaimerClient() {
  const { t } = useLanguage();

  return (
    <div className="max-w-4xl mx-auto py-8 px-2 md:px-6">
      
      {/* Back button */}
      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-foreground transition-colors group"
      >
        <ArrowLeft className="h-4 w-4 group-hover:-translate-x-1 transition-transform" />
        <span>Back to home</span>
      </Link>

      {/* Header card */}
      <div className="rounded-2xl border border-border/40 bg-card/25 backdrop-blur-md p-6 md:p-8 mb-8 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 rounded-full bg-emerald-500/5 blur-2xl pointer-events-none" />
        <div className="flex items-center gap-3 mb-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-500 shadow shadow-emerald-500/10">
            <AlertTriangle className="h-5 w-5" />
          </div>
          <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-500 dark:text-emerald-400">
            Legal Disclaimer
          </span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground font-display">Advisory Disclaimer</h1>
        <p className="text-xs text-muted-foreground mt-2">Last Updated: June 5, 2026</p>
      </div>

      {/* Policy contents */}
      <div className="glass-panel rounded-2xl p-6 md:p-8 space-y-6 text-xs md:text-sm text-muted-foreground leading-relaxed">
        
        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <ShieldAlert className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            1. General Disclaimer
          </h2>
          <p>
            All information provided on the KrishiAI platform, including but not limited to crop predictions, disease diagnoses, mandi prices, government schemes eligibility, and weather advisories, is for informational and educational purposes only.
          </p>
          <p>
            The content is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We make no representations or warranties of any kind, express or implied, as to the accuracy, completeness, or reliability of the AI suggestions generated by the system.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <Leaf className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            2. AI Plant Disease Detection &amp; Recommendations
          </h2>
          <p>
            Our Crop Disease AI processes user-submitted photos to recognize patterns representing leaf damage, insect feeding, or mold. 
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Machine learning models can experience false positives or fail to detect rare disease variants.</li>
            <li>Recommended pesticides, insecticides, fungicides, or organic treatments represent suggestions and must be cross-verified with manufacturers&apos; chemical labels.</li>
            <li>We are not responsible for any crop failure, soil degradation, or physical/financial harm resulting from incorrect chemical application ratios or model error.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <CloudSun className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            3. Weather Intelligence Alerts
          </h2>
          <p>
            Weather data is compiled from third-party meteorological providers. While we utilize automatic failover mechanisms to provide the most recent information, weather forecasting is inherently probabilistic. We cannot be held liable for sudden shifts in temperature, unpredicted rainfall, or hail storms that affect your crops.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            <TrendingUp className="h-4.5 w-4.5 text-emerald-500 shrink-0" />
            4. Live Mandi Prices &amp; Market Alerts
          </h2>
          <p>
            Market prices are updated dynamically based on APMC market dashboards. Due to network latency, geographical differences, and loading variables:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>The prices displayed might lag behind local physical mandi rates.</li>
            <li>Set target notifications are alerts to assist you and are not guaranteed to fire instantly.</li>
            <li>KrishiAI does not guarantee profit margins or bear liability for crop trading losses.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            🏛️ 5. Government Schemes Eligibility &amp; Representation
          </h2>
          <p>
            KrishiAI offers an interactive eligibility tool for central schemes such as PM-Kisan, PMFBY, and KCC. 
          </p>
          <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
            <strong>GOVERNMENT REPRESENTATION DISCLAIMER:</strong> KrishiAI is a private, independent student-led AI application. We are NOT associated, endorsed, or affiliated with the Ministry of Agriculture, the Indian Government, or any State Government agencies. All applications and registration links point to public, official government portals. We do not store or process official application forms or issue direct subsidies.
          </div>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-foreground font-display flex items-center gap-2">
            📞 6. Support Questions
          </h2>
          <p>
            If you require professional agricultural support, we advise consulting with certified botanists, regional APMC officials, or local government agriculture officers. For questions regarding this disclaimer, contact us at: <span className="font-mono text-foreground">adityaoutlier5@gmail.com</span>.
          </p>
        </section>

      </div>
    </div>
  );
}
